export const teams = {
  2025: {
    "Under 7": [
      "Passion Soccer Academy",
      "Millennium Soccer Academy",
      "Nextgen Multi Sports Academy",
      "Phoenix Soccer Academy - Murang'a",
      "Burhan Soccer Academy A",
      "Burhan Soccer Academy B",
      "Faces Sports Academy",
      "Cheza Sports Academy",
      "Rongai Soccer Academy",
      "Insight Football Academy",
      "Ballers of God Academy",
      "Skillz Football Club",
      "Silver Eagle Academy A",
      "Silver Eagle Academy B",
      "Kuza Soccer Academy",
    ],
    "Under 9": [
      "Passion Soccer Academy",
      "Millennium Soccer Academy",
      "LESA",
      "Nextgen Multi Sports Academy A",
      "Nextgen Multi Sports Academy B",
      "Phoenix Soccer Academy - Murang'a",
      "Burhan Soccer Academy A",
      "Burhan Soccer Academy B",
      "Faces Sports Academy",
      "Cheza Sports Academy",
      "Rongai Soccer Academy",
      "Insight Football Academy",
      "Ballers of God Academy",
      "Steplink Soccer Academy - Mombasa",
      "Young City Academy",
      "Masters Soccer Academy",
      "Skillz Football Club",
      "Silver Eagle Academy A",
      "Silver Eagle Academy B",
      "Talent Quest Academy",
      "Dreams Soccer Academy",
      "Ballers Soccer Academy",
      "Kuza Soccer Academy",
    ],
    "Under 11": [
      "Passion Soccer Academy",
      "Millennium Soccer Academy",
      "LESA",
      "Rongai Soccer",
      "Nextgen Multi Sports Academy",
      "Phoenix Soccer Academy - Murang'a",
      "Burhan Soccer Academy A",
      "Burhan Soccer Academy B",
      "Faces Sports Academy",
      "Cheza Sports Academy",
      "Rongai Soccer Academy",
      "Insight Football Academy",
      "Ballers of God Academy",
      "Rangers Soccer Academy",
      "Masters Soccer Academy",
      "Skillz Football Club",
      "Lucky Stars Football Academy",
      "Silver Eagle Academy A",
      "Silver Eagle Academy B",
      "Riverside Academy",
      "Talent Quest Academy",
      "Jaoko Wellness Club",
      "Dreams Soccer Academy",
      "Ballers Soccer Academy",
      "Kuza Soccer Academy",
    ],
    "Under 13": [
      "Passion Soccer Academy",
      "Millennium Soccer Academy",
      "LESA",
      "Rongai Soccer Academy",
      "Nextgen Multi Sports Academy",
      "Phoenix Soccer Academy - Murang'a",
      "Burhan Soccer Academy A",
      "Burhan Soccer Academy B",
      "Faces Sports Academy",
      "Cheza Sports Academy",
      "Rongai Soccer Academy",
      "Insight Football Academy",
      "Ballers of God Academy",
      "Nyalenda Youngstars Academy",
      "Rangers Soccer Academy",
      "Young Boys Soccer Club",
      "Masters Soccer Academy",
      "Skillz Football Club",
      "Silver Eagle Academy",
      "Talent Quest Academy",
      "Dreams Soccer Academy",
      "Ballers Soccer Academy",
      "Kuza Soccer Academy",
    ],
    "Under 15 Boys": [
      "Passion Soccer Academy",
      "Millennium Soccer Academy",
      "UEFA Despanol SC",
      "USSA Elite Academy",
      "Malmo Sports Academy",
      "Elman Football Club",
      "Nextgen Multi Sports Academy",
      "Phoenix Soccer Academy - Murang'a",
      "Faces Sports Academy",
      "Cheza Sports Academy",
      "Rongai Soccer Academy",
      "Insight Football Academy",
      "Ballers of God Academy",
      "Jaoko Wellness Club",
      "Nyalenda Youngstars Academy",
      "Rangers Soccer Academy",
      "Young Boys Soccer Club",
      "Masters Soccer Academy",
      "IBG Sports Academy",
      "Silver Eagle Academy",
      "Riverside Academy",
      "Talent Quest Academy",
      "Dreams Soccer Academy",
      "Ballers Soccer Academy",
      "Kuza Soccer Academy",
    ],
    "Under 17 Boys": [
      "UEFA Despanol SC",
      "USSA Elite Academy",
      "Faces Sports Academy",
      "Rongai Soccer Academy",
      "Malmo Sports Academy",
      "Nyalenda Youngsters Football Club",
      "Phoenix Soccer Academy - Murang'a",
      "Cheza Sports Academy",
      "Young Boys Soccer Club",
      "Rangers Football Academy",
      "Silver Eagle Academy",
      "Mala Soccer group",
      "Jaoko Wellness Club",
      "Dreams Soccer Academy",
    ],
    "Under 20 Boys": [
      "Karatina Football Club",
      "UEFA Despanol SC",
      "Westrand Football Academy",
      "Royal Soccer Academy",
      "Powergen Football Club",
      "Jaoko Wellness Club",
    ],
    "Under 13 Girls": ["Lucky Stars Football Academy"],
    "Under 15 Girls": [
      "Lucky Stars Football Academy",
      "Nyalenda Youngstars Academy",
      "IBG Sports Academy",
      "Cheza Sports Academy",
    ],
    "Under 17 Girls": ["Lucky Stars Football Academy"],
  },
};
